/**
 * Facts published by the Bahrain Athletics Association on https://www.baa.bh
 * (read 5 October 2026). Every record keeps its source URL.
 * Do not add anything here that is not published by BAA or a primary public record.
 */

const BAA = "https://www.baa.bh";
const post = (slug: string) => `${BAA}/post/${slug}`;

export const organisation = {
  name: "Bahrain Athletics Association",
  nameAr: "الاتحاد البحريني لألعاب القوى",
  about:
    "The Bahrain Athletics Association is the official body responsible for organizing and developing athletics in the Kingdom of Bahrain, constantly striving to achieve sporting excellence and raise the Kingdom's profile in regional and international arenas.",
  mission:
    "The Association works to nurture national talent, develop the physical and technical abilities of athletes, and promote a culture of sport as a way of life in Bahraini society.",
  standards:
    "It is committed to applying the highest standards in sports management and encouraging community participation across all age groups.",
  vision:
    "Our vision for the Athletics Federation is to inspire and empower athletes of all levels to achieve their full potential.",
  visionBy: "Mohamed Abdullatif Bin Jalal, President",
  address: "Building 333, Road 435, Block 67, Riffa, Kingdom of Bahrain",
  phone: "+973 17176565",
  email: "brn@mf.worldathletics.org",
  social: {
    instagram: "https://www.instagram.com/baa_bh",
    facebook: "https://www.facebook.com/baabh19",
    x: "https://x.com/baa_bh",
    tiktok: "https://www.tiktok.com/@baa.bh",
  },
  source: `${BAA}/about`,
};

export const board = [
  { name: "Mohamed Abdullatif Bin Jalal", title: "President", group: "executive" },
  { name: "Khalid Mubarak Aldosari", title: "Vice President", group: "executive" },
  { name: "Yousif Ahmed", title: "Secretary General", group: "executive" },
  { name: "Bader Naser", title: "Financial Secretary", group: "executive" },
  { name: "Ruqaya Alghasra", title: "Head of Women Committee", group: "committee" },
  { name: "Mohamed Almahmeed", title: "Head of Media and Development Committee", group: "committee" },
  { name: "Khalid Alqatami", title: "Head of Public Relations", group: "committee" },
  { name: "Mohamed Yusuf Salman", title: "Head of Anti-Doping Committee", group: "committee" },
  { name: "Mohamed Ali Ahmed", title: "Head of the Referees and Competitions", group: "committee" },
  { name: "Mohamed Ali Ahmadi", title: "Head of Investment and Marketing Committee", group: "committee" },
  { name: "Mohammed Abdulaziz", title: "National Team Manager", group: "administration" },
] as const;
export const boardSource = `${BAA}/board-members`;

export const realAthletes = [
  {
    slug: "birhanu-balew",
    firstName: "Birhanu",
    lastName: "Balew",
    gender: "men",
    category: "senior",
    discipline: "5000m",
    headline: "2026 Diamond League 5000m champion",
    bio: "Birhanu Balew won the 2026 Diamond League title in the 5000 metres at the final in Brussels, breaking the Asian and Arab records and recording the world-leading time of the year (12:45.70). He improved on the previous Asian record of 12:47.73, which he had set himself in Oslo in June. Earlier in the season he won the 5000m at the Lausanne Diamond League in 12:57.55.",
    featured: true,
    source: post("birhanu-balew-wins-the-2026-diamond-league-title-and-breaks-the-asian-and-arab-records-for-the-5000m"),
  },
  {
    slug: "winfred-yavi",
    firstName: "Winfred",
    lastName: "Yavi",
    gender: "women",
    category: "senior",
    discipline: "3000m-steeplechase",
    headline: "Olympic champion · 2023 Diamond League title holder",
    bio: "Described by BAA as Bahrain's Olympic champion and the 2023 Diamond League title holder, Winfred Yavi won the women's 3000m steeplechase at the Lausanne Diamond League in August 2026.",
    featured: true,
    source: post("bahraini-olympic-champion-winfred-yafi-achieved-first-place-in-the-women-s-3000m-steeplechase-at-the"),
  },
  {
    slug: "salwa-eid-naser",
    firstName: "Salwa Eid",
    lastName: "Naser",
    gender: "women",
    category: "senior",
    discipline: "400m",
    headline: "Season's best 49.57 · World Athletics Ultimate Championship finalist",
    bio: "Salwa Eid Naser ran a season's best 49.57 to finish third in the women's 400m at the Silesia Diamond League in August 2026, then placed second at the Brescia International Meeting after a photo finish. In September she qualified for the 400m final of the World Athletics Ultimate Championship in Budapest, finishing second in her semi-final in 49.67.",
    featured: true,
    source: post("salwa-eid-naser-finishes-third-in-the-women-s-400m-at-the-diamond-league-recording-her-best-time-th"),
  },
  {
    slug: "naeema-othman",
    firstName: "Naeema",
    lastName: "Othman",
    gender: "women",
    category: "u18",
    discipline: "200m",
    headline: "Arab U18 200m champion 2026",
    bio: "Naeema Othman won gold in the women's under-18 200m at the 12th Arab Athletics Championships for under-18, held at Cairo's Olympic Center in September 2026.",
    featured: true,
    source: post("bahraini-runner-naeema-othman-won-first-place-and-the-gold-medal-in-the-200m-sprint-for-young-women"),
  },
  {
    slug: "ahmed-sabri",
    firstName: "Ahmed",
    lastName: "Sabri",
    gender: "men",
    category: "u23",
    discipline: "high-jump",
    headline: "Arab U23 high jump champion 2026",
    bio: "Ahmed Sabri won gold in the men's high jump at the 3rd Arab Athletics Championship for under 23, held at the Suez Canal Authority Stadium in Ismailia, Egypt.",
    featured: false,
    source: post("champion-ahmed-sabri-wins-the-gold-medal-in-the-men-s-high-jump"),
  },
  {
    slug: "abdikani-ahmed",
    firstName: "Abdikani",
    lastName: "Ahmed",
    gender: "men",
    category: "u23",
    discipline: "5000m",
    headline: "Arab U23 5000m champion 2026",
    bio: "Abdikani Ahmed won gold in the men's 5000m at the 3rd Arab Athletics Championship for under 23 in Ismailia, Egypt.",
    featured: false,
    source: post("champion-abdikani-ahmed-wins-first-place-and-the-gold-medal-in-the-men-s-5000m-race"),
  },
  {
    slug: "ali-haji",
    firstName: "Ali",
    lastName: "Haji",
    gender: "men",
    category: "u23",
    discipline: "100m",
    headline: "Arab U23 silver medallist, 100m and 200m",
    bio: "Ali Haji won silver medals in both the men's 100m and 200m at the 3rd Arab Athletics Championship for under 23 in Ismailia, Egypt.",
    featured: false,
    source: post("champion-ali-haji-wins-the-silver-medal-in-the-men-s-100m-race"),
  },
  {
    slug: "layla-kamal",
    firstName: "Layla",
    lastName: "Kamal",
    gender: "women",
    category: "u23",
    discipline: "100m",
    headline: "Arab U23 100m silver medallist",
    bio: "Layla Kamal won silver in the women's 100m at the 3rd Arab Athletics Championship for under 23 in Ismailia, Egypt.",
    featured: false,
    source: post("champion-layla-kamal-wins-the-silver-medal-in-the-women-s-100m-race"),
  },
  {
    slug: "alreem-fahad",
    firstName: "Alreem",
    lastName: "Fahad",
    gender: "women",
    category: "u16",
    discipline: "long-jump",
    headline: "Arab U16 long jump champion · 80m silver",
    bio: "Alreem Fahad won gold in the long jump and silver in the women's 80m at the 3rd Arab Athletics Championship for under 16 in Ismailia, Egypt.",
    featured: false,
    source: post("champion-alreem-fahad-wins-both-gold-and-silver-medals-in-long-jump-and-in-women-s-80m-race"),
  },
  {
    slug: "fatema-hussain-habib",
    firstName: "Fatema Hussain",
    lastName: "Habib",
    gender: "women",
    category: "u16",
    discipline: "300m",
    headline: "Arab U16 300m bronze medallist",
    bio: "Fatema Hussain Habib won bronze in the women's 300m at the 3rd Arab Athletics Championship for under 16 in Ismailia, Egypt.",
    featured: false,
    source: post("champion-fatema-hussain-habib-wins-the-bronze-medal-in-the-women-s-300m-race"),
  },
  {
    slug: "hassan-yaqoob",
    firstName: "Hassan",
    lastName: "Yaqoob",
    gender: "men",
    category: "u16",
    discipline: "high-jump",
    headline: "Arab U16 high jump bronze medallist",
    bio: "Hassan Yaqoob won bronze in the men's high jump at the 3rd Arab Athletics Championship for under 16 in Ismailia, Egypt.",
    featured: false,
    source: post("champion-hassan-yaqoob-wins-the-bronze-medal-in-the-men-s-high-jump-race"),
  },
] as const;

export const realCompetitions = [
  {
    slug: "diamond-league-final-brussels-2026",
    name: "Wanda Diamond League Final 2026",
    shortName: "DL Final Brussels",
    level: "global",
    city: "Brussels",
    country: "Belgium",
    startDate: "2026-09-04",
    endDate: "2026-09-05",
    status: "completed",
    description: "The season-ending Diamond League final, where Birhanu Balew won the 5000m title with a new Asian and Arab record.",
    image: "stadium",
    source: post("birhanu-balew-wins-the-2026-diamond-league-title-and-breaks-the-asian-and-arab-records-for-the-5000m"),
  },
  {
    slug: "ultimate-championship-budapest-2026",
    name: "World Athletics Ultimate Championship 2026",
    shortName: "Ultimate Championship",
    level: "global",
    city: "Budapest",
    country: "Hungary",
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    status: "completed",
    description: "World Athletics' new invitation-only championship for the season's best athletes. Salwa Eid Naser qualified for the women's 400m final.",
    image: "stadiumSeats",
    source: post("after-a-thrilling-performance-in-the-400m-semi-final-salwa-eid-naser-qualifies-for-the-ultimate-cha"),
  },
  {
    slug: "lausanne-diamond-league-2026",
    name: "Athletissima Lausanne 2026 (Diamond League)",
    shortName: "DL Lausanne",
    level: "meeting",
    city: "Lausanne",
    country: "Switzerland",
    startDate: "2026-08-20",
    endDate: "2026-08-21",
    status: "completed",
    description: "Diamond League meeting in Lausanne. Bahrain won two events: Birhanu Balew in the men's 5000m and Winfred Yavi in the women's 3000m steeplechase.",
    image: "trackField",
    source: post("balew-shines-in-lausanne-and-wins-the-5000m-race-in-the-diamond-league"),
  },
  {
    slug: "silesia-diamond-league-2026",
    name: "Kamila Skolimowska Memorial 2026 (Diamond League)",
    shortName: "DL Silesia",
    level: "meeting",
    city: "Chorzów",
    country: "Poland",
    startDate: "2026-08-23",
    endDate: "2026-08-23",
    status: "completed",
    description: "Diamond League meeting in Silesia where Salwa Eid Naser recorded her season's best in the 400m.",
    image: "stadiumView",
    source: post("salwa-eid-naser-finishes-third-in-the-women-s-400m-at-the-diamond-league-recording-her-best-time-th"),
  },
  {
    slug: "brescia-international-meeting-2026",
    name: "Brescia International Meeting 2026",
    shortName: "Brescia",
    level: "meeting",
    city: "Brescia",
    country: "Italy",
    startDate: "2026-08-29",
    endDate: "2026-08-29",
    status: "completed",
    description: "International meeting where Salwa Eid Naser took second place in the 400m after a photo finish.",
    image: "race",
    source: post("after-a-thrilling-and-dramatic-finish-decided-by-a-photo-finish-salwa-eid-nasser-shines-at-the-bres"),
  },
  {
    slug: "arab-u18-championships-2026",
    name: "12th Arab Athletics Championships U18",
    shortName: "Arab U18 Champs",
    level: "regional",
    city: "Cairo",
    country: "Egypt",
    venue: "Cairo Olympic Center",
    startDate: "2026-09-05",
    endDate: "2026-09-09",
    status: "completed",
    description: "Regional youth championships for Arab nations. Naeema Othman won the women's 200m.",
    image: "sprintStart",
    source: post("bahraini-runner-naeema-othman-won-first-place-and-the-gold-medal-in-the-200m-sprint-for-young-women"),
  },
  {
    slug: "arab-u23-championships-2026",
    name: "3rd Arab Athletics Championship U23",
    shortName: "Arab U23 Champs",
    level: "regional",
    city: "Ismailia",
    country: "Egypt",
    venue: "Suez Canal Authority Stadium",
    startDate: "2026-06-23",
    endDate: "2026-06-25",
    status: "completed",
    description: "Bahrain's U23 team won gold in the men's high jump and 5000m, and silver in the men's 100m, men's 200m and women's 100m. Dates reflect BAA's reports.",
    image: "raceStart",
    source: post("champion-ahmed-sabri-wins-the-gold-medal-in-the-men-s-high-jump"),
  },
  {
    slug: "arab-u16-championships-2026",
    name: "3rd Arab Athletics Championship U16",
    shortName: "Arab U16 Champs",
    level: "regional",
    city: "Ismailia",
    country: "Egypt",
    venue: "Suez Canal Authority Stadium",
    startDate: "2026-06-24",
    endDate: "2026-06-25",
    status: "completed",
    description: "Bahrain's U16 athletes won gold in the women's long jump, silver in the women's 80m, and bronze in the women's 300m and men's high jump. Dates reflect BAA's reports.",
    image: "longJump",
    source: post("champion-alreem-fahad-wins-both-gold-and-silver-medals-in-long-jump-and-in-women-s-80m-race"),
  },
  {
    slug: "asian-games-aichi-nagoya-2026",
    name: "20th Asian Games Aichi-Nagoya 2026",
    shortName: "Asian Games",
    level: "continental",
    city: "Nagoya",
    country: "Japan",
    startDate: "2026-09-19",
    endDate: "2026-10-04",
    status: "completed",
    description: "Bahrain's national athletics team prepared with a training camp in Kuala Lumpur, Malaysia. Results will be published here once confirmed by BAA.",
    image: "stadium",
    source: post("in-preparation-for-the-asian-games-in-aichi-nagoya-the-athletics-team-is-departing-for-malaysia-for"),
  },
  {
    slug: "gcc-games-doha-2026",
    name: "4th GCC Games",
    shortName: "GCC Games",
    level: "regional",
    city: "Doha",
    country: "Qatar",
    venue: "Qatar Sports Club",
    startDate: "2026-05-11",
    endDate: "2026-05-22",
    status: "completed",
    description: "A premier multi-sport event bringing together elite athletes from the six Gulf Cooperation Council (GCC) nations.",
    image: "emptyTrack",
    source: `${BAA}/events`,
  },
  {
    slug: "west-asia-championships-riffa",
    name: "West Asia Athletics Championships",
    shortName: "West Asia Champs",
    level: "regional",
    city: "Riffa",
    country: "Bahrain",
    startDate: null,
    endDate: null,
    status: "postponed",
    description: "Due to the current regional situation, the Championship has been postponed until further notice.",
    image: "lanes",
    source: `${BAA}/events`,
  },
  {
    slug: "world-championships-tokyo-2025",
    name: "World Athletics Championships Tokyo 25",
    shortName: "Worlds Tokyo",
    level: "global",
    city: "Tokyo",
    country: "Japan",
    startDate: "2025-09-13",
    endDate: "2025-09-21",
    status: "completed",
    description: "Listed by BAA among the national team's international participations.",
    image: "stadiumSeats",
    source: BAA,
  },
  {
    slug: "islamic-solidarity-games-riyadh-2025",
    name: "6th Islamic Solidarity Games",
    shortName: "Islamic Solidarity Games",
    level: "continental",
    city: "Riyadh",
    country: "Saudi Arabia",
    startDate: "2025-11-07",
    endDate: "2025-11-20",
    status: "completed",
    description: "Listed by BAA among the national team's international participations.",
    image: "trackCurve",
    source: BAA,
  },
  {
    slug: "olympic-games-paris-2024",
    name: "Olympic Games Paris 2024",
    shortName: "Paris 2024",
    level: "global",
    city: "Paris",
    country: "France",
    startDate: "2024-08-01",
    endDate: "2024-08-11",
    status: "completed",
    description: "Athletics programme of the Games of the XXXIII Olympiad.",
    image: "stadium",
    source: BAA,
  },
] as const;

/** Results as reported by BAA. `mark: null` means BAA did not publish the mark. */
export const realResults = [
  { athlete: "birhanu-balew", competition: "diamond-league-final-brussels-2026", discipline: "5000m", round: "final", position: 1, mark: "12:45.70", record: "AR", date: "2026-09-04", notes: "Asian and Arab record; world lead", source: post("birhanu-balew-wins-the-2026-diamond-league-title-and-breaks-the-asian-and-arab-records-for-the-5000m") },
  { athlete: "birhanu-balew", competition: "lausanne-diamond-league-2026", discipline: "5000m", round: "final", position: 1, mark: "12:57.55", date: "2026-08-21", source: post("balew-shines-in-lausanne-and-wins-the-5000m-race-in-the-diamond-league") },
  { athlete: "winfred-yavi", competition: "lausanne-diamond-league-2026", discipline: "3000m-steeplechase", round: "final", position: 1, mark: null, date: "2026-08-21", source: post("bahraini-olympic-champion-winfred-yafi-achieved-first-place-in-the-women-s-3000m-steeplechase-at-the") },
  { athlete: "salwa-eid-naser", competition: "silesia-diamond-league-2026", discipline: "400m", round: "final", position: 3, mark: "49.57", isSB: true, date: "2026-08-23", source: post("salwa-eid-naser-finishes-third-in-the-women-s-400m-at-the-diamond-league-recording-her-best-time-th") },
  { athlete: "salwa-eid-naser", competition: "brescia-international-meeting-2026", discipline: "400m", round: "final", position: 2, mark: null, date: "2026-08-29", notes: "Decided by photo finish", source: post("after-a-thrilling-and-dramatic-finish-decided-by-a-photo-finish-salwa-eid-nasser-shines-at-the-bres") },
  { athlete: "salwa-eid-naser", competition: "ultimate-championship-budapest-2026", discipline: "400m", round: "semi-final", position: 2, mark: "49.67", date: "2026-09-11", notes: "Qualified for the final", source: post("after-a-thrilling-performance-in-the-400m-semi-final-salwa-eid-naser-qualifies-for-the-ultimate-cha") },
  { athlete: "naeema-othman", competition: "arab-u18-championships-2026", discipline: "200m", round: "final", position: 1, medal: "gold", mark: null, date: "2026-09-08", source: post("bahraini-runner-naeema-othman-won-first-place-and-the-gold-medal-in-the-200m-sprint-for-young-women") },
  { athlete: "ahmed-sabri", competition: "arab-u23-championships-2026", discipline: "high-jump", round: "final", position: 1, medal: "gold", mark: null, date: "2026-06-23", source: post("champion-ahmed-sabri-wins-the-gold-medal-in-the-men-s-high-jump") },
  { athlete: "ali-haji", competition: "arab-u23-championships-2026", discipline: "100m", round: "final", position: 2, medal: "silver", mark: null, date: "2026-06-23", source: post("champion-ali-haji-wins-the-silver-medal-in-the-men-s-100m-race") },
  { athlete: "layla-kamal", competition: "arab-u23-championships-2026", discipline: "100m", round: "final", position: 2, medal: "silver", mark: null, date: "2026-06-23", source: post("champion-layla-kamal-wins-the-silver-medal-in-the-women-s-100m-race") },
  { athlete: "ali-haji", competition: "arab-u23-championships-2026", discipline: "200m", round: "final", position: 2, medal: "silver", mark: null, date: "2026-06-25", source: post("champion-ali-haji-wins-the-silver-medal-in-the-men-s-200m-race") },
  { athlete: "abdikani-ahmed", competition: "arab-u23-championships-2026", discipline: "5000m", round: "final", position: 1, medal: "gold", mark: null, date: "2026-06-25", source: post("champion-abdikani-ahmed-wins-first-place-and-the-gold-medal-in-the-men-s-5000m-race") },
  { athlete: "alreem-fahad", competition: "arab-u16-championships-2026", discipline: "long-jump", round: "final", position: 1, medal: "gold", mark: null, date: "2026-06-24", source: post("champion-alreem-fahad-wins-both-gold-and-silver-medals-in-long-jump-and-in-women-s-80m-race") },
  { athlete: "alreem-fahad", competition: "arab-u16-championships-2026", discipline: "80m", round: "final", position: 2, medal: "silver", mark: null, date: "2026-06-24", source: post("champion-alreem-fahad-wins-both-gold-and-silver-medals-in-long-jump-and-in-women-s-80m-race") },
  { athlete: "fatema-hussain-habib", competition: "arab-u16-championships-2026", discipline: "300m", round: "final", position: 3, medal: "bronze", mark: null, date: "2026-06-25", source: post("champion-fatema-hussain-habib-wins-the-bronze-medal-in-the-women-s-300m-race") },
  { athlete: "hassan-yaqoob", competition: "arab-u16-championships-2026", discipline: "high-jump", round: "final", position: 3, medal: "bronze", mark: null, date: "2026-06-24", source: post("champion-hassan-yaqoob-wins-the-bronze-medal-in-the-men-s-high-jump-race") },
] as const;

export const realAchievements = [
  { title: "Diamond League 5000m champion", description: "Won the 2026 Diamond League title in Brussels in 12:45.70, an Asian and Arab record and the year's world lead.", year: 2026, date: "2026-09-04", type: "title", athlete: "birhanu-balew", competition: "diamond-league-final-brussels-2026", featured: true, source: post("birhanu-balew-wins-the-2026-diamond-league-title-and-breaks-the-asian-and-arab-records-for-the-5000m") },
  { title: "Asian record, 5000m: 12:45.70", description: "Improved his own Asian record of 12:47.73 (Oslo, June 2026) by more than two seconds.", year: 2026, date: "2026-09-04", type: "record", athlete: "birhanu-balew", competition: "diamond-league-final-brussels-2026", featured: true, source: post("birhanu-balew-wins-the-2026-diamond-league-title-and-breaks-the-asian-and-arab-records-for-the-5000m") },
  { title: "Olympic champion, 3000m steeplechase", description: "Winfred Yavi is described by BAA as Bahrain's Olympic champion.", year: 2024, date: "2024-08-06", type: "medal", medal: "gold", athlete: "winfred-yavi", competition: "olympic-games-paris-2024", featured: true, source: post("bahraini-olympic-champion-winfred-yafi-achieved-first-place-in-the-women-s-3000m-steeplechase-at-the") },
  { title: "Lausanne double", description: "Bahrain won the men's 5000m (Balew) and the women's 3000m steeplechase (Yavi) at the Lausanne Diamond League.", year: 2026, date: "2026-08-21", type: "milestone", competition: "lausanne-diamond-league-2026", featured: true, source: post("balew-shines-in-lausanne-and-wins-the-5000m-race-in-the-diamond-league") },
  { title: "Arab U18 200m gold", description: "Naeema Othman won the women's under-18 200m at the 12th Arab Athletics Championships in Cairo.", year: 2026, date: "2026-09-08", type: "medal", medal: "gold", athlete: "naeema-othman", competition: "arab-u18-championships-2026", featured: false, source: post("bahraini-runner-naeema-othman-won-first-place-and-the-gold-medal-in-the-200m-sprint-for-young-women") },
  { title: "Five medals at the Arab U23 Championship", description: "Two gold (high jump, 5000m) and three silver (men's 100m, men's 200m, women's 100m) in Ismailia.", year: 2026, date: "2026-06-25", type: "milestone", competition: "arab-u23-championships-2026", featured: true, source: post("champion-ahmed-sabri-wins-the-gold-medal-in-the-men-s-high-jump") },
] as const;

export const realNews = [
  {
    slug: "balew-diamond-league-title-asian-record",
    title: "Balew wins Diamond League title with a new Asian record",
    excerpt: "Birhanu Balew won the 2026 Diamond League 5000m title in Brussels in 12:45.70, breaking the Asian and Arab records and setting the year's world lead.",
    body: "Bahraini runner Birhanu Balew won the 2026 Diamond League title in the 5000 metres at the final held in Brussels, Belgium.\n\nHe broke both the Asian and Arab records and recorded the best time in the world this year, crossing the line in 12:45.70.\n\nBalew broke the previous Asian record of 12:47.73, which he himself had set in Oslo last June, improving his time by more than two seconds.",
    category: "achievements",
    image: "stadium",
    publishedAt: "2026-09-05",
    featured: true,
    athletes: ["birhanu-balew"],
    competition: "diamond-league-final-brussels-2026",
    source: post("birhanu-balew-wins-the-2026-diamond-league-title-and-breaks-the-asian-and-arab-records-for-the-5000m"),
  },
  {
    slug: "naser-qualifies-ultimate-championship-final",
    title: "Naser books her place in the Ultimate Championship 400m final",
    excerpt: "Salwa Eid Naser finished second in her semi-final in 49.67 to reach the 400m final in Budapest.",
    body: "Salwa Eid Naser has qualified for the 400m final at the World Athletics Ultimate Championship in Budapest, Hungary.\n\nShe finished second in her semi-final with a time of 49.67 seconds.\n\nThe final takes place on Saturday 12 September against a field of the world's top 400m runners.",
    category: "competitions",
    image: "stadiumSeats",
    publishedAt: "2026-09-12",
    featured: false,
    athletes: ["salwa-eid-naser"],
    competition: "ultimate-championship-budapest-2026",
    source: post("after-a-thrilling-performance-in-the-400m-semi-final-salwa-eid-naser-qualifies-for-the-ultimate-cha"),
  },
  {
    slug: "national-team-training-camp-kuala-lumpur",
    title: "National team opens its Kuala Lumpur training camp",
    excerpt: "Photos from the first day of the national athletics team's camp in the Malaysian capital, ahead of the Asian Games.",
    body: "The national athletics team began its training camp in Kuala Lumpur, Malaysia, as part of its preparation for the 20th Asian Games in Aichi-Nagoya.",
    category: "federation",
    image: "emptyTrack",
    publishedAt: "2026-09-12",
    featured: false,
    athletes: [],
    competition: "asian-games-aichi-nagoya-2026",
    source: post("photos-from-the-first-day-of-our-national-athletics-team-s-training-camp-in-the-malaysian-capital-k"),
  },
  {
    slug: "team-departs-malaysia-asian-games-preparation",
    title: "Team departs for Malaysia to prepare for Aichi-Nagoya",
    excerpt: "The athletics team travelled to Malaysia for an intensive training camp ahead of the Asian Games.",
    body: "In preparation for the Asian Games in Aichi-Nagoya, the athletics team departed for Malaysia for an intensive training camp.",
    category: "international",
    image: "lanes",
    publishedAt: "2026-09-10",
    featured: false,
    athletes: [],
    competition: "asian-games-aichi-nagoya-2026",
    source: post("in-preparation-for-the-asian-games-in-aichi-nagoya-the-athletics-team-is-departing-for-malaysia-for"),
  },
  {
    slug: "naeema-othman-arab-u18-200m-gold",
    title: "Naeema Othman wins Arab U18 200m gold",
    excerpt: "The young sprinter took first place on day four of the 12th Arab Athletics Championships for under-18 in Cairo.",
    body: "Bahraini runner Naeema Othman won first place and the gold medal in the 200m sprint for young women during the fourth day of the 12th Arab Athletics Championships for under-18.\n\nThe championships were held at Cairo's Olympic Center from 5 to 9 September 2026.\n\nHer victory adds another achievement to Bahrain's participation in the Arab Championships.",
    category: "athletes",
    image: "sprintStart",
    publishedAt: "2026-09-10",
    featured: false,
    athletes: ["naeema-othman"],
    competition: "arab-u18-championships-2026",
    source: post("bahraini-runner-naeema-othman-won-first-place-and-the-gold-medal-in-the-200m-sprint-for-young-women"),
  },
  {
    slug: "bin-jalal-congratulates-leadership-balew",
    title: "Bin Jalal congratulates the leadership on Balew's global achievement",
    excerpt: "The BAA President congratulated His Majesty the King and His Royal Highness the Crown Prince and Prime Minister on Birhanu Balew's title.",
    body: "Bin Jalal congratulated His Majesty the King and His Royal Highness the Crown Prince and Prime Minister on the global achievement of Bahraini runner Birhanu Balew.",
    category: "federation",
    image: "trackCurve",
    publishedAt: "2026-09-09",
    featured: false,
    athletes: ["birhanu-balew"],
    competition: "diamond-league-final-brussels-2026",
    source: post("bin-jalal-congratulates-his-majesty-the-king-and-his-royal-highness-the-crown-prince-and-prime-minis"),
  },
  {
    slug: "team-departs-egypt-arab-u18-championships",
    title: "Youth team departs for the Arab U18 Championships in Egypt",
    excerpt: "The national team travelled to Egypt for the 12th Arab Athletics Championships for under-18.",
    body: "The Bahrain national athletics team departed for the Arab Republic of Egypt to participate in the 12th Arab Athletics Championships for under-18.",
    category: "international",
    image: "raceStart",
    publishedAt: "2026-09-03",
    featured: false,
    athletes: [],
    competition: "arab-u18-championships-2026",
    source: post("the-bahrain-national-athletics-team-departed-today-to-the-arab-republic-of-egypt-to-participate-in-t"),
  },
  {
    slug: "naser-second-brescia-photo-finish",
    title: "Naser second in Brescia after a photo finish",
    excerpt: "Salwa Eid Naser took second place in the 400m at the Brescia International Meeting in a finish decided by the photo.",
    body: "After a dramatic finish decided by a photo finish, Salwa Eid Naser secured second place in the 400m at the Brescia International Meeting.",
    category: "competitions",
    image: "race",
    publishedAt: "2026-08-30",
    featured: false,
    athletes: ["salwa-eid-naser"],
    competition: "brescia-international-meeting-2026",
    source: post("after-a-thrilling-and-dramatic-finish-decided-by-a-photo-finish-salwa-eid-nasser-shines-at-the-bres"),
  },
  {
    slug: "naser-third-silesia-season-best",
    title: "Naser third in Silesia with a season's best 49.57",
    excerpt: "Salwa Eid Naser finished third in the women's 400m at the Silesia Diamond League, her fastest time of the season.",
    body: "Bahraini runner Salwa Eid Naser finished third in the women's 400m at the Silesia Diamond League in Poland.\n\nNaser completed the race in 49.57 seconds, her best time of the season.",
    category: "athletes",
    image: "stadiumView",
    publishedAt: "2026-08-23",
    featured: false,
    athletes: ["salwa-eid-naser"],
    competition: "silesia-diamond-league-2026",
    source: post("salwa-eid-naser-finishes-third-in-the-women-s-400m-at-the-diamond-league-recording-her-best-time-th"),
  },
  {
    slug: "balew-wins-lausanne-5000m",
    title: "Balew wins the 5000m in Lausanne",
    excerpt: "Birhanu Balew won a close Diamond League 5000m in 12:57.55, ahead of Parker Wolff and Nico Young.",
    body: "Bahraini athlete Birhanu Balew won the 5000m at the 2026 Lausanne Diamond League in Switzerland.\n\nBalew secured a hard-fought victory in 12:57.55, ahead of American Parker Wolff (12:58.20) and fellow American Nico Young (12:58.33).",
    category: "competitions",
    image: "trackField",
    publishedAt: "2026-08-22",
    featured: false,
    athletes: ["birhanu-balew"],
    competition: "lausanne-diamond-league-2026",
    source: post("balew-shines-in-lausanne-and-wins-the-5000m-race-in-the-diamond-league"),
  },
  {
    slug: "yavi-wins-steeplechase-lausanne",
    title: "Olympic champion Yavi wins the steeplechase in Lausanne",
    excerpt: "Winfred Yavi won the women's 3000m steeplechase at the 2026 Lausanne Diamond League.",
    body: "Bahraini Olympic champion Winfred Yavi took first place in the women's 3000m steeplechase at the Lausanne Diamond League 2026 in Switzerland.\n\nYavi, the 2023 Diamond League title holder, won against an elite field.",
    category: "athletes",
    image: "hurdles",
    publishedAt: "2026-08-22",
    featured: false,
    athletes: ["winfred-yavi"],
    competition: "lausanne-diamond-league-2026",
    source: post("bahraini-olympic-champion-winfred-yafi-achieved-first-place-in-the-women-s-3000m-steeplechase-at-the"),
  },
  {
    slug: "abdikani-ahmed-arab-u23-5000m-gold",
    title: "Abdikani Ahmed wins Arab U23 5000m gold",
    excerpt: "Gold for Bahrain in the men's 5000m at the 3rd Arab Athletics Championship for under 23 in Ismailia.",
    body: "Abdikani Ahmed won first place and the gold medal in the men's 5000m at the 3rd Arab Athletics Championship for under 23, held at the Suez Canal Authority Stadium in Ismailia, Egypt.",
    category: "achievements",
    image: "legs",
    publishedAt: "2026-06-25",
    featured: false,
    athletes: ["abdikani-ahmed"],
    competition: "arab-u23-championships-2026",
    source: post("champion-abdikani-ahmed-wins-first-place-and-the-gold-medal-in-the-men-s-5000m-race"),
  },
  {
    slug: "alreem-fahad-arab-u16-gold-silver",
    title: "Alreem Fahad takes long jump gold and 80m silver",
    excerpt: "Two medals for Alreem Fahad at the 3rd Arab Athletics Championship for under 16.",
    body: "Alreem Fahad won gold in the long jump and silver in the women's 80m at the 3rd Arab Athletics Championship for under 16, held at the Suez Canal Authority Stadium in Ismailia, Egypt.",
    category: "development",
    image: "longJump",
    publishedAt: "2026-06-24",
    featured: false,
    athletes: ["alreem-fahad"],
    competition: "arab-u16-championships-2026",
    source: post("champion-alreem-fahad-wins-both-gold-and-silver-medals-in-long-jump-and-in-women-s-80m-race"),
  },
  {
    slug: "ahmed-sabri-arab-u23-high-jump-gold",
    title: "Ahmed Sabri wins Arab U23 high jump gold",
    excerpt: "Gold in the men's high jump for Ahmed Sabri in Ismailia.",
    body: "Ahmed Sabri won the gold medal in the men's high jump at the 3rd Arab Athletics Championship for under 23, held at the Suez Canal Authority Stadium in Ismailia, Egypt.",
    category: "achievements",
    image: "heritageJump",
    publishedAt: "2026-06-23",
    featured: false,
    athletes: ["ahmed-sabri"],
    competition: "arab-u23-championships-2026",
    source: post("champion-ahmed-sabri-wins-the-gold-medal-in-the-men-s-high-jump"),
  },
] as const;

export const cleanAthleticsLinks = {
  bnado: "https://b-nado.bh/report-doping/",
  aiu: "https://www.athleticsintegrity.org/make-a-report",
  wada: "https://www.wada-ama.org/",
  wadaSpeakUp: "https://speakup.wada-ama.org/",
};
